; TjofiaWeatherStation — ESP32 Huzzah32 / Adafruit Feather ESP32

[common]
platform  = espressif32
board     = featheresp32
framework = arduino
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=1

[env:featheresp32]
extends = common
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
lib_deps =
    tzapu/WiFiManager @ ^2.0.17
    bblanchon/ArduinoJson @ ^7.0.4
    adafruit/Adafruit GFX Library @ ^1.11.0
