; TjofiaWeatherStation — ESP32 Huzzah32 / Adafruit Feather ESP32
[env:featheresp32]
platform  = espressif32
board     = featheresp32
framework = arduino

monitor_speed          = 115200
board_build.filesystem = spiffs

lib_deps =
    tzapu/WiFiManager @ ^2.0.17
    bblanchon/ArduinoJson @ ^7.0.4
    moononournation/GFX Library for Arduino @ ^1.4.9

build_flags =
    -DCORE_DEBUG_LEVEL=1
